### PR TITLE
add cloud v0.6.0

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Review by itowlson — CHANGES_REQUESTED** [review]
I believe this needs to come in as `cloud.json` and the existing `cloud.json` needs to move to `cloud@v0.5.1.json`.  The file without the decorator should be the current one.

**Comment by bacongobbler** [comment]
Ah! Thank you for the correction. Fixing

**Comment by bacongobbler** [comment]
@itowlson quick question: is there any reason I shouldn't create cloud@v0.6.0 at the same time as I update cloud.json? I figured that would give users a way to pin to the current version.

**Review by itowlson — APPROVED** [review]

**Comment by itowlson** [comment]
@bacongobbler There are places where we scan the list of manifests (e.g. `spin plugins search`) and I think Spin could get confused if there were two manifests with the same version.  I'm sure we could fix these to deduplicate, and it would make it easier to follow the diffs.  I don't think we need it for pinning, though - I added something around badger time to make `-v` work correctly for the current version.

**Pull request merged**
