### PR TITLE
Update trigger-kinesis to 0.2 version

### PR DESCRIPTION
**Pull request by ogghead**
Signed-off-by: Darwin Boersma <darwin@sprout.org>

### CODE REVIEW

**Review by vdice — APPROVED** [review]
🎉 Thanks @ogghead!

**Review by vdice — CHANGES_REQUESTED** [review]
@ogghead Oops, sorry, I forgot we usually like to preserve all releases for a plugin.

Could you create a `trigger-kinesis@0.1.0.json` file holding the 0.1.0 json?  The update to `trigger-kinesis.json` with 0.2.0 release data can stay the same.

Here's an example PR doing similar: https://github.com/fermyon/spin-plugins/pull/66

**Comment by ogghead** [comment]
Good callout, will update with that shortly and keep it in mind for future releases!

**Review by vdice — APPROVED** [review]
Thanks for the last minute changes!  LGTM.

**Pull request merged**
